import './globals.css'
import type { Metadata } from 'next'
import { ReactElement } from 'react'
import FetcherProvider from '~/components/FetcherProvider'
import AuthProvider from '~/providers/AuthProvider'
import { inter } from '~/utils/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout ({
  children
}: {
  children: React.ReactNode
}): Promise<ReactElement> {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <AuthProvider>
          <FetcherProvider>
            {children}
          </FetcherProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
